import {
  Wallet, TrendingUp, Target, AlertTriangle, Clock, Activity,
  DollarSign, Users, Package, FileCheck, BarChart3, Gauge,
  CalendarClock, Receipt, ShoppingCart, Factory,
} from "lucide-react";
import type { WidgetDefinition } from "./types";

export const WIDGET_REGISTRY: Record<string, WidgetDefinition> = {
  "caixa-hoje": {
    id: "caixa-hoje",
    title: "Caixa hoje",
    description: "Saldo consolidado das contas bancárias",
    category: "financeiro",
    defaultSize: "sm",
    profiles: ["owner", "financeiro"],
    icon: Wallet,
    drillPath: "/financeiro/contas-bancarias",
  },
  "lucro-projetado": {
    id: "lucro-projetado",
    title: "Lucro projetado",
    description: "Resultado projetado do período",
    category: "estrategico",
    defaultSize: "md",
    profiles: ["owner"],
    icon: TrendingUp,
    drillPath: "/bi/dre",
  },
  "runway": {
    id: "runway",
    title: "Runway",
    description: "Meses de operação com caixa atual",
    category: "estrategico",
    defaultSize: "sm",
    profiles: ["owner"],
    icon: Gauge,
  },
  "margem-contribuicao": {
    id: "margem-contribuicao",
    title: "Margem contribuição",
    description: "Margem de contribuição do mês",
    category: "estrategico",
    defaultSize: "sm",
    profiles: ["owner", "financeiro"],
    icon: BarChart3,
    drillPath: "/bi/dre",
  },
  "forecast-vendas": {
    id: "forecast-vendas",
    title: "Forecast de vendas",
    description: "Previsão para o mês corrente",
    category: "comercial",
    defaultSize: "md",
    profiles: ["owner", "comercial"],
    icon: TrendingUp,
    drillPath: "/crm",
  },
  "prioridades-semana": {
    id: "prioridades-semana",
    title: "Prioridades da semana",
    description: "Ações sugeridas pela IA",
    category: "estrategico",
    defaultSize: "md",
    profiles: ["owner"],
    icon: Target,
  },
  "contas-vencendo": {
    id: "contas-vencendo",
    title: "Contas vencendo",
    description: "Contas a pagar próximas do vencimento",
    category: "financeiro",
    defaultSize: "sm",
    profiles: ["owner", "financeiro"],
    icon: CalendarClock,
    drillPath: "/contas-pagar",
  },
  "contas-vencidas": {
    id: "contas-vencidas",
    title: "Contas vencidas",
    description: "Atrasos em contas a pagar",
    category: "financeiro",
    defaultSize: "sm",
    profiles: ["owner", "financeiro"],
    icon: AlertTriangle,
    drillPath: "/contas-pagar",
  },
  "conciliacao-pendente": {
    id: "conciliacao-pendente",
    title: "Conciliação pendente",
    description: "Movimentações sem conciliação",
    category: "financeiro",
    defaultSize: "sm",
    profiles: ["financeiro"],
    icon: Receipt,
    drillPath: "/conciliacao-bancaria",
  },
  "fluxo-caixa": {
    id: "fluxo-caixa",
    title: "Fluxo de caixa",
    description: "Entradas e saídas dos próximos dias",
    category: "financeiro",
    defaultSize: "lg",
    profiles: ["owner", "financeiro"],
    icon: Activity,
    drillPath: "/bi/fluxo-caixa",
  },
  "inadimplencia": {
    id: "inadimplencia",
    title: "Inadimplência",
    description: "Recebíveis em atraso",
    category: "financeiro",
    defaultSize: "sm",
    profiles: ["financeiro", "owner"],
    icon: AlertTriangle,
    drillPath: "/contas-receber",
  },
  "dre-resumida": {
    id: "dre-resumida",
    title: "DRE resumida",
    description: "Receita, custos e resultado",
    category: "financeiro",
    defaultSize: "lg",
    profiles: ["owner", "financeiro"],
    icon: BarChart3,
    drillPath: "/bi/dre",
  },
  "pipeline": {
    id: "pipeline",
    title: "Pipeline",
    description: "Oportunidades por etapa",
    category: "comercial",
    defaultSize: "lg",
    profiles: ["comercial", "owner"],
    icon: Users,
    drillPath: "/crm",
  },
  "propostas-abertas": {
    id: "propostas-abertas",
    title: "Propostas abertas",
    description: "Propostas aguardando decisão",
    category: "comercial",
    defaultSize: "sm",
    profiles: ["comercial"],
    icon: FileCheck,
    drillPath: "/pedidos",
  },
  "conversao": {
    id: "conversao",
    title: "Conversão",
    description: "Taxa de conversão do funil",
    category: "comercial",
    defaultSize: "sm",
    profiles: ["comercial", "owner"],
    icon: TrendingUp,
  },
  "ticket-medio": {
    id: "ticket-medio",
    title: "Ticket médio",
    description: "Valor médio por venda",
    category: "comercial",
    defaultSize: "sm",
    profiles: ["comercial", "owner"],
    icon: DollarSign,
  },
  "meta-comercial": {
    id: "meta-comercial",
    title: "Meta comercial",
    description: "Atingimento da meta do período",
    category: "comercial",
    defaultSize: "md",
    profiles: ["comercial", "owner"],
    icon: Target,
    drillPath: "/metas",
  },
  "projetos-ativos": {
    id: "projetos-ativos",
    title: "Projetos ativos",
    description: "Projetos em andamento",
    category: "operacional",
    defaultSize: "sm",
    profiles: ["operacional", "owner"],
    icon: Package,
    drillPath: "/projetos",
  },
  "ordens-atrasadas": {
    id: "ordens-atrasadas",
    title: "OPs atrasadas",
    description: "Ordens de produção em atraso",
    category: "operacional",
    defaultSize: "sm",
    profiles: ["operacional", "owner"],
    icon: AlertTriangle,
    drillPath: "/producao-operacoes",
  },
  "producao-andamento": {
    id: "producao-andamento",
    title: "Produção em andamento",
    description: "OPs por etapa",
    category: "operacional",
    defaultSize: "lg",
    profiles: ["operacional"],
    icon: Factory,
    drillPath: "/producao-operacoes",
  },
  "tarefas-criticas": {
    id: "tarefas-criticas",
    title: "Tarefas críticas",
    description: "Tarefas com prazo crítico",
    category: "operacional",
    defaultSize: "md",
    profiles: ["operacional"],
    icon: Clock,
    drillPath: "/tarefas",
  },
  "health-score": {
    id: "health-score",
    title: "Health score",
    description: "Saúde geral do negócio",
    category: "estrategico",
    defaultSize: "sm",
    profiles: ["owner"],
    icon: Gauge,
  },
  "pedidos-aguardando": {
    id: "pedidos-aguardando",
    title: "Pedidos aguardando",
    description: "Pedidos pendentes de aprovação/produção",
    category: "operacional",
    defaultSize: "sm",
    profiles: ["operacional", "comercial"],
    icon: ShoppingCart,
    drillPath: "/pedidos",
  },
};

export const DEFAULT_LAYOUTS: Record<"owner" | "financeiro" | "comercial" | "operacional", string[]> = {
  owner: [
    "caixa-hoje", "lucro-projetado", "runway", "health-score",
    "margem-contribuicao", "forecast-vendas",
    "fluxo-caixa", "dre-resumida",
    "prioridades-semana", "meta-comercial",
  ],
  financeiro: [
    "caixa-hoje", "contas-vencendo", "contas-vencidas", "inadimplencia",
    "conciliacao-pendente", "margem-contribuicao",
    "fluxo-caixa", "dre-resumida",
  ],
  comercial: [
    "propostas-abertas", "conversao", "ticket-medio", "pedidos-aguardando",
    "meta-comercial", "forecast-vendas",
    "pipeline",
  ],
  operacional: [
    "projetos-ativos", "ordens-atrasadas", "pedidos-aguardando",
    "tarefas-criticas",
    "producao-andamento",
  ],
};
