DROP POLICY IF EXISTS "Tenant read own financial diagnoses" ON public.ai_financial_diagnoses;
CREATE POLICY "Tenant read own financial diagnoses" ON public.ai_financial_diagnoses FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant manage own simulations" ON public.ai_impact_simulations;
CREATE POLICY "Tenant manage own simulations" ON public.ai_impact_simulations FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own operational diagnoses" ON public.ai_operational_diagnoses;
CREATE POLICY "Tenant read own operational diagnoses" ON public.ai_operational_diagnoses FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own priority actions" ON public.ai_priority_actions;
CREATE POLICY "Tenant read own priority actions" ON public.ai_priority_actions FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own strategy alerts" ON public.ai_strategy_alerts;
CREATE POLICY "Tenant read own strategy alerts" ON public.ai_strategy_alerts FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own percentile scores" ON public.benchmark_percentile_scores;
CREATE POLICY "Tenant read own percentile scores" ON public.benchmark_percentile_scores FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own recommendations" ON public.benchmark_recommendations;
CREATE POLICY "Tenant read own recommendations" ON public.benchmark_recommendations FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own events" ON public.billing_events;
CREATE POLICY "Tenant read own events" ON public.billing_events FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own activation" ON public.customer_activation;
CREATE POLICY "Tenant read own activation" ON public.customer_activation FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own adoption" ON public.customer_adoption;
CREATE POLICY "Tenant read own adoption" ON public.customer_adoption FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own health" ON public.customer_health_scores;
CREATE POLICY "Tenant read own health" ON public.customer_health_scores FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own onboarding" ON public.customer_onboarding;
CREATE POLICY "Tenant read own onboarding" ON public.customer_onboarding FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own certifications" ON public.education_certifications;
CREATE POLICY "Tenant read own certifications" ON public.education_certifications FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own recommendations" ON public.education_recommendations;
CREATE POLICY "Tenant read own recommendations" ON public.education_recommendations FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant isolation for assets" ON public.fin_assets;
CREATE POLICY "Tenant isolation for assets" ON public.fin_assets FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant isolation for business events" ON public.fin_business_events;
CREATE POLICY "Tenant isolation for business events" ON public.fin_business_events FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Users can manage tenant history" ON public.fin_classification_history;
CREATE POLICY "Users can manage tenant history" ON public.fin_classification_history FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Users can view tenant history" ON public.fin_classification_history;
CREATE POLICY "Users can view tenant history" ON public.fin_classification_history FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Users can manage tenant rules" ON public.fin_classification_rules;
CREATE POLICY "Users can manage tenant rules" ON public.fin_classification_rules FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Users can view tenant rules" ON public.fin_classification_rules;
CREATE POLICY "Users can view tenant rules" ON public.fin_classification_rules FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant isolation for depreciation" ON public.fin_depreciation_schedule;
CREATE POLICY "Tenant isolation for depreciation" ON public.fin_depreciation_schedule FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant isolation for loan installments" ON public.fin_loan_installments;
CREATE POLICY "Tenant isolation for loan installments" ON public.fin_loan_installments FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant isolation for origin rules" ON public.fin_origin_rules;
CREATE POLICY "Tenant isolation for origin rules" ON public.fin_origin_rules FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant isolation fin_permission_profiles" ON public.fin_permission_profiles;
CREATE POLICY "Tenant isolation fin_permission_profiles" ON public.fin_permission_profiles FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant isolation fin_profile_permissions" ON public.fin_profile_permissions;
CREATE POLICY "Tenant isolation fin_profile_permissions" ON public.fin_profile_permissions FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "tenant_isolation_recurring_timeline" ON public.fin_recurring_contract_timeline;
CREATE POLICY "tenant_isolation_recurring_timeline" ON public.fin_recurring_contract_timeline FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant isolation for recurring contracts" ON public.fin_recurring_contracts;
CREATE POLICY "Tenant isolation for recurring contracts" ON public.fin_recurring_contracts FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant isolation fin_user_finance_profiles" ON public.fin_user_finance_profiles;
CREATE POLICY "Tenant isolation fin_user_finance_profiles" ON public.fin_user_finance_profiles FOR ALL TO authenticated USING (public.tenant_rls_check(tenant_id)) WITH CHECK (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own invoices" ON public.invoices;
CREATE POLICY "Tenant read own invoices" ON public.invoices FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own history" ON public.subscription_history;
CREATE POLICY "Tenant read own history" ON public.subscription_history FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own subscription" ON public.subscriptions;
CREATE POLICY "Tenant read own subscription" ON public.subscriptions FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));
DROP POLICY IF EXISTS "Tenant read own usage" ON public.usage_consumption;
CREATE POLICY "Tenant read own usage" ON public.usage_consumption FOR SELECT TO authenticated USING (public.tenant_rls_check(tenant_id));